// LS AI — how-to guide for the LS TECH app, written from SYSTEM.md. Each section: { key, label, path, text }.
// `path` must be a real screen (it is the only kind of link the assistant may show). Keep text short and exact.
const GUIDE = [
  { key: 'home', label: 'Home: tasks and calendar', path: '/', text: 'Home shows your follow-up tasks (left) and a Week / Month / Year calendar (right). Admin and manager can switch Mine / All and assign a task by clicking the avatar. Click Done to complete a task (use Undo in the toast to reopen it). Click a day to see its tasks and quick-add a new one. Click a task to edit its title or due date, read the contact and last note, or "Log this call" (note + next touchpoint). Invoice-review tasks can be approved or rejected by admin or manager. The Watch List shows high-severity clients.' },
  { key: 'clients', label: 'Clients: contacts and pipeline', path: '/clients', text: 'Clients lists your CRM contacts with KPIs and a pipeline by stage (new, contacted, qualified, customer, lost). Use the search box, the status chips (with counts) and Filters (product, designation, severity). Click Add to create a client; click a name to edit it, log a call note and schedule the next touchpoint. Select rows and use Delete selected for bulk delete.' },
  { key: 'catalog', label: 'Catalog: items', path: '/catalog', text: 'Catalog is the master item list. Add an item with its code, description and default SPQ (pieces per reel). Edit or Delete (archive) from the table. An archived item cannot receive new stock; adding the same code again restores it. With a store selected in the top bar, the list shows only items that have been stocked at that store.' },
  { key: 'inward', label: 'Inward: receive reels', path: '/inward', text: 'Inward receives new stock. Pick the item, enter the number of reels and boxes (0 boxes = loose reels), choose the receiving store and submit. Admin and manager actions run immediately; staff submissions wait in Requests for approval. After receiving, print reel or box labels (PDF with QR codes). Recent Inward lets you reprint labels, and admin/manager can undo.' },
  { key: 'outward', label: 'Outward: ship reels', path: '/outward', text: 'Outward ships stock. Scan reels or boxes (camera or scanner) or type the numbers to fill the cart, choose the customer (autocomplete from the CRM) and optionally a purchase order, then Submit. A packing-list PDF is produced and can be reprinted from Recent Outwards. A reel is always shipped from the store where it is. Undo is for admin and manager only.' },
  { key: 'transfer', label: 'Transfer: move stock between stores', path: '/transfer', text: 'Transfer moves reels or boxes between LS Tech Stores and Gelco Stores. Scan or type reels/boxes into the cart, set From store, To store and notes, then submit. A box moves as one unit only when all its in-stock reels are in the cart; otherwise its reels move individually. Recent Transfers has a date filter and a PDF export; admin and manager can undo a transfer.' },
  { key: 'reports_stock', label: 'Reports: Stock Summary', path: '/reports', text: 'Reports → Stock Summary shows each item with total reels, in-stock reels and in-stock quantity, for the store selected at the top (or all stores). Use the date box to see stock as on a past date, and export CSV.' },
  { key: 'reports_search', label: 'Reports: Search & Trace', path: '/reports/search', text: 'Search & Trace finds reels by reel number, item, box, customer or invoice from one search box, with status and date filters. Each row shows the outward history. You can export what is on screen to CSV. Admin and manager can soft-delete reels or boxes (password required).' },
  { key: 'reports_analytics', label: 'Reports: Analytics', path: '/reports/analytics', text: 'Analytics shows monthly inward vs outward trends, stock aging, top customers and an inventory timeline, filtered by the selected store. Click an item for its monthly trend.' },
  { key: 'reports_alerts', label: 'Reports: Dead & Low Stock', path: '/reports/alerts', text: 'Dead & Low Stock lists items that have not shipped in 30 days (dead stock) and items with fewer than 5 reels in stock (low stock), for the selected store.' },
  { key: 'reports_daily', label: 'Reports: Daily Report', path: '/reports/daily', text: 'Daily Report shows one day\'s inward, outward and transfers by item, plus dead and low stock counts and pending approvals, for the selected store. Pick a date and use Download PDF.' },
  { key: 'requests', label: 'Requests: approvals', path: '/requests', text: 'Requests lists inward, outward and transfer requests submitted by staff. Admin and manager can Approve, Reject (with a reason) or Edit & approve. The bell in the top bar shows how many are waiting.' },
  { key: 'notifications', label: 'Notifications: outward log', path: '/notifications', text: 'Notifications lists every outward event with date filters and a search box. The second bell in the top bar shows today\'s outward count. Admin and manager only.' },
  { key: 'gelco_gate', label: 'Gelco daily approval', path: '/outward', text: 'Gelco Manager and Gelco Worker accounts are locked to Gelco Stores. Each day the Gelco Manager must approve yesterday\'s outward summary before any Gelco user can inward, outward or transfer. Admin and manager are exempt. Gelco users only see Catalog, Outward, Docs and Stocks.' },
  { key: 'docs', label: 'Docs: PO and invoice PDFs', path: '/gelco-docs', text: 'Docs stores PO and invoice PDFs privately. Choose a file and the type (PO or Invoice) and upload; only PDFs are accepted. Use Download or Delete in the list. The list follows the store selected at the top.' },
  { key: 'settings', label: 'Settings: users, storage, LS AI', path: '/settings', text: 'Settings (admin and manager) manages users and roles, shows storage use for the database and file storage, and — for admin only — the LS AI card: OpenRouter key, credit, model, daily limit and data-access approval.' },
  { key: 'stores', label: 'Stores and the store dropdown', path: '/reports', text: 'There are two stores: LS Tech Stores and Gelco Stores. The dropdown in the top bar only filters what you view; it does not decide where stock is created or shipped from. Inward, Transfer and Outward have their own store fields.' },
];
const SCREENS = [...new Map(GUIDE.map((g) => [g.path, g.label])).keys(), '/notifications'];
const SCREEN_LABEL = { '/': 'Home', '/clients': 'Clients', '/catalog': 'Catalog', '/inward': 'Inward', '/outward': 'Outward', '/transfer': 'Transfer', '/reports': 'Stock Summary', '/reports/search': 'Search & Trace', '/reports/analytics': 'Analytics', '/reports/alerts': 'Dead & Low Stock', '/reports/daily': 'Daily Report', '/requests': 'Requests', '/notifications': 'Notifications', '/gelco-docs': 'Docs', '/settings': 'Settings' };

// Cheap keyword shortlist (no model): label hits weigh more than text hits.
function pickSections(question, limit = 8) {
  const ws = [...new Set(String(question).toLowerCase().match(/[a-z0-9]{3,}/g) || [])];
  return GUIDE.map((g) => {
    const label = g.label.toLowerCase(), text = g.text.toLowerCase();
    return { g, score: ws.reduce((a, w) => a + (label.includes(w) ? 4 : 0) + (text.includes(w) ? 1 : 0), 0) };
  }).filter((x) => x.score > 0).sort((a, b) => b.score - a.score).slice(0, limit).map((x) => x.g);
}

module.exports = { GUIDE, SCREENS, SCREEN_LABEL, pickSections };
